name: build markdown

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nwylynko/markdown-add-files@master
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: README builder
          message: 'Updated Readme'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}